name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install surge and fire deployment
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: ${{ secrets.SURGE_DOMAIN }}
          token: ${{ secrets.SURGE_TOKEN }}
      - name: Install Packages
        run: yarn install
        run: yarn build:export
